### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by josepman** [Neurita/neuro_docker#1]
Hi!

I discover your docker in BraincHack Bilbao  (thanks to Asier and Ibai ;) ).
I have installed docker and all tools operating, but files and directories I transferred from my local machine (with docker run -it -v <host_path>:<guest_path> dockerfile/neuro) appear in black in the terminal (Basic, Homebrew, Gras....all of them). Attached is a snapshot show them.

![captura de pantalla 2017-03-03 a las 18 10 29](https://cloud.githubusercontent.com/assets/20078436/23561033/de3d98d0-003c-11e7-9c2a-561766cf3e59.png)

![captura de pantalla 2017-03-03 a las 18 20 45](https://cloud.githubusercontent.com/assets/20078436/23561334/25bd9b28-003e-11e7-8b33-3b74df90c330.png)

Do you know how can I solve that?

Thank you!!
josepman@ucm.es
---
OSX 10.11.6

**Comment by alexsavio** [comment]
Hi @josepman,

I have never seen that problem. What Terminal app are you using? Have you tried using another?
I don't think it is something caused by the container OS, I am not sure. :/

**Comment by josepman** [comment]
Hi @alexsavio ,

I don't know what it happened. I just tried with iTerm and this problem was solved.

Another issue to your concern is the possibility to include Octave (or Matlab for personal use) in this container. We have commands from Octave in some scripts that we can't use.

Thank you!

**Comment by alexsavio** [comment]
Hi,
Yes, you could also install octave if you wish. The script is already installing the Matlab compiler runtime MCR to run SPM12.
I wanted to keep things small as possible, although the container is quite large still.
Octave would add another gigabyte, wouldn't it? :/
